### PR TITLE
Dynamic URL for meetup results.

### PR DESCRIPTION
**Pull request by CurtainUp**
git checkout -b ed-dynamicUrl
git pull origin ed-dynamicUrl

Created unique element builder for meetups to display dynamic URL. Created unique injection function. Set target to open in new tab.

### CODE REVIEW

**Comment by CurtainUp** [comment]
Hey all! Pushed a new version that injects the Meetup info dynamically into the itinerary. I had to add an extra property to our JSON object.

**Comment by jasehackman** [comment]
Ahhhh that makes sense.

#Crushedit!

**Comment by jasehackman** [comment]
oops I hit the wrong thing and actually closed it. This is all good.

**Comment by robbyhecht** [comment]
looking good Elyse 👍

**Comment by jasehackman** [comment]
Boom

**Comment by robbyhecht** [comment]
this is working for me 🙌

**Pull request merged**
