### PR TITLE
make more options for searchs as well as some styling 

### PR DESCRIPTION
**Pull request by wesseln1**
if anyone wants to change anything on the styling feel free too. Just did it as an idea for everyone to look at.

git checkout -b nw-fine-tune-parks
git pull origin nw-fine-tune-parks

### CODE REVIEW

**Comment by jasehackman** [comment]
Great job on adding the extra search options!

With the styling, I think the center justification on the search results and itinerary makes them a little difficult to read. I would love to see more options on the styling.

**Comment by jasehackman** [comment]
I think it would look cool to have the search and results on the left side, and if we could get the itinerary to appear on the right side.

**Comment by CurtainUp** [comment]
Messed with the bg color and made it lighter than the bold blue at it's darkest. Added a header font and body font. 

I was unable to figure out moving the itinerary to the right. I also tried adding an empty --Search-- option to each dropdown but was still getting search results in spite of an if statement so I left the menus as they are.

**Comment by jasehackman** [comment]
If you wrap everything in the body in a div, except for the main header and give it its own class. 

Then use the following for styling that class: 
 display: flex;
  justify-content: space-around;

That gets it most of the way there, but still might need some final tweaking.

**Pull request closed without merging**
